project: 'ssod_runs/percent'
name: '20per'
adam: False
epochs: 200
weights: 'sup_runs/percent/20per2/weights/best.pt'
prune_finetune: False
linear_lr: True
cache: True

hyp:
  lr0: 0.01
  lrf: 1.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  scale: 0.9
  translate: 0.1
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.1
  warmup_epochs: 0
  no_aug_epochs: 0
  burn_epochs: 0

Model:
  depth_multiple: 0.33  # model depth multiple
  width_multiple: 0.25  # layer channel multiple
  Backbone: 
    name: 'YoloV5'
    activation: 'SiLU'
  Neck: 
    name: 'YoloV5' 
    in_channels: [256, 512, 1024]
    out_channels: [256, 512, 1024]
    activation: 'SiLU'
  Head: 
    name: 'YoloV5'
    activation: 'SiLU'
  anchors: [[10,13, 16,30, 33,23],[30,61, 62,45, 59,119],[116,90, 156,198, 373,326]]  # P5/32]
Loss:
  type: 'ComputeLoss'

Dataset:
  data_name: 'vehicle'
  train: data/train_20.txt  # 4000 images
  target: data/unlabeled.txt
  val: data/val.txt  # 1218 images
  test: data/val.txt # 0 of 5218 images
  nc: 7  # number of classes
  np: 0 #number of keypoints
  names: ['car', 'van', 'truck', 'suv', 'light truck', 'tanker', 'bus']
  img_size: 640
  batch_size: 32
  workers : 8

SSOD:
  train_domain: True
  nms_conf_thres: 0.1
  nms_iou_thres: 0.7
  teacher_loss_weight: 0.5
  cls_loss_weight: 0.3
  box_loss_weight: 0.05
  obj_loss_weight: 0.7
  pseudo_label_type : 'LabelMatch'
  loss_type: 'ComputeStudentMatchLoss'
  ignore_thres_low: 0.6
  ignore_thres_high: 0.6
  uncertain_aug: True
  use_ota: False
  multi_label: False
  ignore_obj: True
  pseudo_label_with_obj: True
  pseudo_label_with_bbox: True
  pseudo_label_with_cls: False
  with_da_loss: False
  da_loss_weights: 0.01
  epoch_adaptor: True
  resample_high_percent: 0.25
  resample_low_percent: 0.99
  ema_rate: 0.99 
  cosine_ema: True
  imitate_teacher: False
  # dynamic_thres: True
  ssod_hyp:
    with_gt: False
    mosaic: 1.0
    cutout: 0.5
    autoaugment: 0.5
    scale: 0.8
    degrees: 0.0
    shear: 0.0
